# Loops & Orbits &mdash; Week 2 &mdash; Day 4 &mdash; Numpy Tutorial

There is a [numpy Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html). I borrowed from it to get started writing a tutorial for you. Personally, I think that what I have created for you emphasizes the concepts more clearly. However, theirs is longer and more complete and it is part of scipy's official documentation, so perhaps you'll want to look at it after working through my quickstart below.

## Rationale for Numpy

The Python List is not designed for the highest level of numerical performance.

You can tell this because things like this are possible:

In [ ]:
my_list = [1, "Loki", 2.0, ("Physics", "Math", "Computer Science")]

my_list

As you can see a list can take inhomogeneous mixtures of items &mdash; items of different types. Above, we have an integer, a string, a float, and a tuple which in turn contains three strings.

If you are very familiar with how things are implemented on computers, you know this is not optimal for speed even though it is optimal for flexibility.

Anybody who does scientific computing switches over from lists to numpy's ndarrays in order to make their programs run faster and to work with all their colleagues who are using numpy.

## Numpy Basics

### Multi-Dimensional and High Performance

NumPy’s main object is called ndarray. It is homogeneous and multi-dimensional. It stands for n-dimensional array. Because it is homogeneous it is almost as high performance as C-language arrays. Fortran is still the gold standard for speed, but nobody knows Fortan nowadays, and fewer and fewer people know C. So numpy and ndarray exist because Python users need a high-performance array.

### Contrast with Ordinary List

By contrast with ndarray, Python lists are one-dimensional. That just means they take a single index:

In [ ]:
my_list[1] ## a list takes one index

In [ ]:
my_list[2] ## the index can be anything from 0 to len(my_list - 1)

In [ ]:
my_list[-1] ## a special notation for getting the last item

### Example: An `ndarray` of Zeros

Let's make a numpy array that takes two indices and starts off with all zeros.

In [ ]:
# You know that import brings in optional libraries.
# By bringing in the library "as np" our prefixes for library functions aren't as long.

import numpy as np

all_zeros = np.zeros((3, 4))  ## The np library function that creates an array of all zeros.

all_zeros[1, 2] # check that out -- it takes two indices!

# also note that the preceding is not all_zeros(1, 2)
# accessing elements takes indices, not function arguments

Just like Python lists, the indices number from 0.

So in the `all_zeros` array, the first index goes from 0 to 2 and the second index goes from 0 to 3.

In [ ]:
# Let's put the second index out of bounds:

all_zeros[1, 4] # should fail

### Rows and Columns

An array that takes two indices is said to be two-dimensional ro to have two axes.

For two-dimensional arrays it is easy to have a mental picture of a grid of numbers. (For 3-dimensional and higher it is harder to have a mental picture. 3-dimensional arrays you could imagine a cube of numbers but often that isn't very helpful in understanding the code.)

In the two-dimensional case, the rows in the grid are specified by the first axis (which is axis 0).

The columns of the grid are specified by the second axis (which is axis 1).

So our all_zeros array has 3 rows and 4 columns. *Don't picture this as 3 columns and 4 rows or you will not be in agreement with the convention for displaying two-dimensional arrays.*

Here is how Python and Jupyter display our 3x4 all_zeros array:

In [ ]:
all_zeros

### An `ndarray` of Ascending Integers

In [ ]:
# The following is intentionally similar to the range function:
ascending = np.arange(0, 15)

ascending

## Array Shape and Reshaping

Apparently `ascending` is alot like a 1-axis list that runs from 0 to 14.

We can reshape it!

If we make it have three rows and five columns, will we get:
    
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])
```

or will we get

```
array([[0, 3, 6,  9, 12],
       [1, 4, 7, 10, 13],
       [2, 5, 8, 11, 14]])
```

We just try it:

In [ ]:
ascending = ascending.reshape(3, 5)

ascending

This is very significant. It tells us that ndarray things of the last axis as the one that is changing 
most rapidly. It's just like digits when you count. The last digit changes most rapidly.

```
6458
6459
6460
6461
6462
```

That's just a convention. We could have had the first digit change the most rapidly

```
6458
7458
8458
9458
0558
```

That's looks very weird, because we are so used to have the least significant digit be on the right. But it
is just a convention. On some other planet, the accountants might put the least-significant digit on the left.

As it is with digits, it is with numpy. The elements in ascending order have the least significant index on the right:

```
ascending[0, 0]
ascending[0, 1]
ascending[0, 2]
ascending[0, 3]
ascending[0, 4]
ascending[1, 0]
ascending[1, 1]
ascending[1, 2]
ascending[1, 3]
ascending[1, 4]
ascending[2, 0]
ascending[2, 1]
ascending[2, 2]
ascending[2, 3]
ascending[2, 4]
```

So the sixth element is the [1, 0] element and it better be 5.

In [ ]:
ascending[1, 0]

### Misleading Method

`reshape` is really a misleading function to be showing you. It seems to take a variable number of 
positional arguments. A different and less common way of calling `reshape` is:

In [ ]:
new_ascending = np.arange(0, 30)

new_ascending.reshape((6, 5)) # note the extra parens that make the first argument a tuple rather than two arguments

In [ ]:
# How about a three-axis `ndarray`

new_ascending.reshape((2, 3, 5)) # this could have been called as new_ascending.reshape(2, 3, 5)

The bottom line is that reshape is kind of an unconventional example. It is unconvential because 
it is written in C for performance, see the [Stack Overlow discussion](https://stackoverflow.com/questions/46508340/passing-new-shape-to-np-reshape) if you want to go way deeper.
Only look at that if you are having a really easy time with the Python (most likely if you have
learned and used it elsewhere).

Back to our two-dimensional `ndarray` made from the 15-element ascending to see another surprise:

### Reshaping Makes a Copy

Let's make ascending have 5 rows and 3 columns

Then let's access element [4, 1]. Something will go wrong.

In [ ]:
ascending.reshape(5, 3)

In [ ]:
ascending[4, 1]

What went wrong?

```
ascending.reshape(5, 3)
```

seemed like it did what we wanted.

However, it made a copy of itself. It did not change itself. Instead

```
ascending.reshape(5, 3)
```

returned the copy and we did not save the copy anywhere.

Usually when you reshape you want the copy not the original, so you reshape and overwrite the original as follows:

In [ ]:
ascending = ascending.reshape(5, 3)

ascending

Now we are able to access row 4, column 1 of ascending:

In [ ]:
ascending[4, 1]

### Transposition

It seems a little annoying that we don't yet have a way of getting this array:

```
array([[0, 3, 6,  9, 12],
       [1, 4, 7, 10, 13],
       [2, 5, 8, 11, 14]])
```

Here is how to do it:

In [ ]:
ascending = np.arange(0, 15)

ascending = ascending.reshape(5, 3)

ascending

# we are not there yet -- the special we sauce we need is the transpose method
# a method is a function on an object -- you are free to be sloppy and say transpose function

In [ ]:
np.transpose(ascending)

As with reshape, transpose made and returned a copy.

So we have lost our change:

In [ ]:
ascending

Here is how to keep the copy:

In [ ]:
ascending = np.transpose(ascending)

ascending

## Assignment in Lists and `ndarray`
    
Lists and numpy arrays are both mutable. In all the code we have done so far, we have been modifying our lists
by appending to them. We have not needed to go back and change a value. Here's how you change a value in a list:

In [ ]:
my_list = [1, 2, 59, 8, 16, 32, 64]

my_list[2] = 4

my_list

That probably made fine sense

### You cannot append to `ndarray`

However you can change values totally analagously to the way values in lists are changed:

In [ ]:
jackpot = np.arange(0, 15).reshape(3, 5)

jackpot[2, 0] = 20
jackpot[2, 1] = 22
jackpot[2, 2] = 24
jackpot[2, 3] = 26
jackpot[2, 4] = 28

jackpot

## Vectorized Operations

I haven't yet gotten to one of the main reasons why numpy is high-performance!

It supports vectorized operations, and this means that all the processors (also known as cores) on a multi-processor computer can work in parallel.

For the Python list, this is *illegal*:

In [ ]:
times = [0.0, 0.1, 0.2, 0.3]

stopwatch_start_time = 5.0

times = times + stopwatch_start_time

You wish that would have returned

```
[5.0, 5.1, 5.2, 5.3]
```

Let's try the same thing with ndarray:

In [ ]:
times = np.arange(0.0, 0.4, 0.1)

times

You can already tell that richer things than can happen in standard Python are happening.

This wasn't even legal with the ordinary range function:

In [ ]:
range(0.0, 0.4, 0.1)

Anyway, we have our ndarray of times. Now let's see what we can get away with it:

In [ ]:
times = times + stopwatch_start_time

times

So unlike a list you can add a float to every element in the list, which in this case is exactly what we wanted.

Here's more stuff you can do that cannot be done with the standard Python lists:

In [ ]:
# the following illustrates a new function that converts a list to an ndarray

some_numbers_to_cube = np.array([2.0, 4.0, 6.0, 8.0]) 
some_numbers_to_cube

In [ ]:
some_numbers_to_cube**3

You can see that ndarray allows you to do things very cleanly and clearly that aren't even legal with the ordinary Python list.

I always argue against compact code that is unclear. Compact code that is clean and clear is the best of all worlds.

As usual, you get a copy and the original is unmodified. You've lost your changes:

In [ ]:
some_numbers_to_cube

So don't forget to save the reference to your new list:

In [ ]:
cubed_numbers = some_numbers_to_cube**3

cubed_numbers

## Random Numbers and Histograms

Almost anything you could want to do in science including statistical analysis is possible with numpy.

Let's make a lot of random numbers:

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

# Sample a normal distribution 10000 times with standard deviation of 0.5 and mean of 2.0

mu = 2.0
sigma = 0.5
great_gobs = 10000

samples = np.random.normal(mu, sigma, great_gobs)

samples

We just made 10,000 samples. Fortunately Jupyter knows not to print them all. It omitted a lot with ... notation.

Let's plot the samples:

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

# Use matplotlib histogram function
plt.hist(samples)
plt.show()

In [ ]:
# Want more detail?
# As usual with a histogram you can decide how finely spaced you want your bins to be.
# The default is 10. This bumps it up to 50:
plt.hist(samples, bins=50)
plt.show()

In [ ]:
# Want it normalized?
# This makes the total area under the curve 1.
plt.hist(samples, bins=50, density=1)
plt.show()

## Conclusion


You have seen a ton of new stuff. Continuing to learn the features of numpy with the SciPy [numpy Quickstart tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html) would be one way to continue if you want to learn more.